# Generated by Django 3.1.3 on 2020-11-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Artista')),
                ('telefono', models.CharField(max_length=13, verbose_name='Teléfono ')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Categoría')),
                ('nomCategoria', models.CharField(max_length=30, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('numero', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='N° serie')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripción')),
                ('modelo', models.CharField(max_length=20, null=True, verbose_name='modelo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEVA.categoria')),
            ],
        ),
    ]
