# Generated by Django 3.1.3 on 2020-11-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEVA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintura',
            name='descripcion',
            field=models.CharField(max_length=30, verbose_name='Nombre Pintura'),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='modelo',
            field=models.CharField(max_length=20, null=True, verbose_name='Modelo'),
        ),
    ]
