# Generated by Django 3.1.3 on 2020-11-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEVA', '0002_auto_20201116_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='telefono',
        ),
        migrations.AddField(
            model_name='artista',
            name='email',
            field=models.EmailField(default='a', max_length=50, verbose_name='Email Artista '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='password',
            field=models.CharField(default='a', max_length=15, verbose_name='Password Artista'),
            preserve_default=False,
        ),
    ]
