# Generated by Django 3.1.3 on 2020-11-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppEVA', '0003_auto_20201116_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Foto')),
                ('texto', models.CharField(max_length=120, verbose_name='Texto Foto')),
                ('fechaRegistro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEVA.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.DeleteModel(
            name='Pintura',
        ),
    ]
