# Generated by Django 3.1.3 on 2020-11-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEVA', '0004_auto_20201116_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
